[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.20.3",
    "modulegraph>=0.19.6",
    "pytest>=8.3.4",
    "python-vlc>=3.0.21203",
    "rich>=13.9.4",
]
